# Generated by Django 5.2 on 2025-04-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_campaign_mailinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcontact',
            name='engaged',
            field=models.BooleanField(default=False),
        ),
    ]
