# Generated by Django 5.2 on 2025-04-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_emailcontact_engaged'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='mailing_lists',
            field=models.ManyToManyField(related_name='campaigns', to='marketing.mailinglist'),
        ),
    ]
