# Generated by Django 5.2 on 2025-04-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_campaign_current_step_campaign_total_steps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='EmailObject',
        ),
        migrations.AddField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
