# Generated by Django 5.2 on 2025-04-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_rename_email_emailobject_campaign_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='mailing_lists',
            field=models.ManyToManyField(blank=True, null=True, related_name='campaigns', to='marketing.mailinglist'),
        ),
    ]
