# Generated by Django 5.2 on 2025-04-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_alter_campaign_mailing_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='mailing_lists',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='marketing.mailinglist'),
        ),
    ]
