# Generated by Django 5.2 on 2025-05-08 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0011_alter_campaign_mailing_lists'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_a', models.CharField(max_length=255)),
                ('subject_b', models.CharField(max_length=255)),
                ('template', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='marketing.campaign')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_email_templates', to='marketing.emailtemplate')),
            ],
            options={
                'unique_together': {('campaign', 'template')},
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='templates',
            field=models.ManyToManyField(blank=True, related_name='campaigns', through='marketing.CampaignEmailTemplate', to='marketing.emailtemplate'),
        ),
    ]
