# Generated by Django 5.2 on 2025-05-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0012_emailtemplate_campaignemailtemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='total_steps',
            field=models.IntegerField(default=0),
        ),
    ]
