# Generated by Django 5.2 on 2025-05-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0013_alter_campaign_total_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='next_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
