# Generated by Django 5.2 on 2025-05-13 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0014_schedule_last_run_schedule_next_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailobject',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='marketing.campaign'),
        ),
    ]
