# Generated by Django 5.2 on 2025-05-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0015_emailobject_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailobject',
            name='replied',
            field=models.BooleanField(default=False),
        ),
    ]
