# Generated by Django 5.2 on 2025-05-16 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0016_emailobject_replied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='name',
        ),
    ]
