# Generated by Django 5.2 on 2025-05-19 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0017_remove_schedule_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email_name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('reputation_score', models.FloatField(default=1.0)),
                ('daily_send_limit', models.IntegerField(default=20)),
                ('sent_today', models.IntegerField(default=0)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='emailcontact',
            name='last_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.sendingprofile'),
        ),
    ]
