# Generated by Django 5.2 on 2025-05-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0019_sendingprofile_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendingprofile',
            name='title',
            field=models.CharField(default='Marketing', max_length=255),
        ),
    ]
