# Generated by Django 5.2 on 2025-06-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0020_sendingprofile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
